enableRobotsTXT = true
# baseurl = "./" # local only
baseurl = "https://pablowoodward.com/" #{{ .Site.BaseURL }} "/" && netlify
# relativeURLs = "true" #https://github.com/gohugoio/hugo/issues/985
languageCode = "en" #Initial configuration reset #languageCode = "en-us"
title = "Pablo Woodward"
image = "img/JC1.jpg" #JC1.jpg
#logo = "/favicon.png" #DEL, this doesn't render?!
copyright = "InspiredLabs.co.uk" # © = http://www.theukwebdesigncompany.com/articles/entity-escape-characters.php

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[Params]
  logo = "favicon.png" #{{ with .Site.Params.logo }}{{ . }}{{ end }}
  email = "pablo@pablowoodward.com"
  keywords = ["Actor", "Presenter", "Comedian", "Kids Entertainer", "Childrens Entertainer", "2016 DBS Certified", "UK Equity Member", "AUS MEAA Member", "The Royal Opera", "theatre", "Brighton", "London", "culture", "The Disco Bunny", "Kasabian", "energetic", "Latino", "Latin American", "Black", "Mixed Race", "multilingual", "Latino" ]
  description = """Ethnically ambiguous probable Latino. Insatiable energy to explore, adventure & learn. Bold Linguistic Artist Extraordinaire!""" #<160 thing for SERP
  SiteDescription = "UK Equity Member | AUS MEAA Member"
  
  #linkedin = "theurbanaut"
  #cover = "/img/background-cover.jpg"

[author]
  type = "person" #https://www.mandy.com/actor/profile/pablowoodward
  name = "Pablo Woodward"
  #itemid = "#pablowoodward" #`seo.html` has: "$id": "{{ .Site.BaseURL }}"
  email = "pablo@pablowoodward.com"
  image = "https://pablowoodward.com/M55128.0122.jpg" #M55128.0122.jpg, M55128.0122.jpg, JC1.jpg, favicon.png
  homepage = "https://pablowoodward.com/"
  facebook = "https://www.facebook.com/pablo.woodward/" #"inspiredlabs"
  twitter = "pablowoodward" #https://twitter.com/PabloWoodward/, "inspiredlabs"
	bio = """Actor, Presenter, Comedian & ethnically ambiguous probable Latino with an insatiable energy to explore, adventure & learn: Bold Linguistic Artist Extraordinaire.""" #"""multi-line""" #https://discourse.gohugo.io/t/how-to-access-site-params-map-with-a-params-variable/348/2
