# baseurl = "./" # local only
baseurl = "https://pablowoodward.netlify.com/" #{{ .Site.BaseURL }} "/" && netlify
# relativeURLs = "true" #https://github.com/gohugoio/hugo/issues/985
languageCode = "en-gb" #Initial configuration reset #languageCode = "en-us"
title = "Pablo Woodward"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[Params]
  #github = "inspiredlabs"
  #twitter = "inspiredlabs"
  email = "pablo@pablowoodward.com"
  SiteDescription = "UK Equity Member | AUS MEAA Member"
  #linkedin = "theurbanaut"
  #cover = "/img/background-cover.jpg"
  #logo = "/img/logo-1.jpg"
